#!/bin/bash

words=(":)" "Linux" "cyb3r" "#Darkxx" "Tuxify" "tuxic" "Arch Btw !!" "rag0n1z3d" "L0L!!" "th3v3z" "bankai" "Gh0s1")

# Generate a random index
random_index=$(( RANDOM % ${#words[@]} ))

# Get the random tech word
word=${words[$random_index]}

# Display the tech word in figlet font
figlet -f new "$word"
